# Generated by Django 4.2.3 on 2023-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipy',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
