# Generated by Django 4.2.3 on 2023-07-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipySite', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recepies',
        ),
        migrations.AddField(
            model_name='recipy',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipySite.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recipy',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
