# Generated by Django 4.2.3 on 2023-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipySite', '0004_remove_category_recepies_recipy_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipy',
            name='title',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
